refactor: setup ovs in container
host node does not need to install ovs anymore

diff --git a/build/script/init_agent b/build/script/init_agent
--- a/build/script/init_agent
+++ b/build/script/init_agent
@@ -1,5 +1,7 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
+# init cni
+echo "init cni"
 mkdir -p /var/run/everoute
 chmod 755 /var/run/everoute
 
@@ -12,6 +14,36 @@ rm -f /etc/cni/net.d/10-everoute.conf
 rm -f /etc/cni/net.d/10-everoute.conflist
 install -m 644 /var/lib/everoute/cni-conf.conflist /etc/cni/net.d/10-everoute.conflist
 
+# init ovs
+echo "init ovs"
+modprobe openvswitch || (echo "modprobe openvswitch error"; exit 1)
+
+source /usr/share/openvswitch/scripts/ovs-lib
+
+OVS_DB_FILE="/var/run/everoute/openvswitch.db"
+
+function start_ovs {
+    if daemon_is_running ovsdb-server; then
+        echo "ovsdb-server is already running"
+    else
+        echo "Starting ovsdb-server"
+        /usr/share/openvswitch/scripts/ovs-ctl --no-ovs-vswitchd --system-id=random start --db-file=$OVS_DB_FILE
+        echo "Started ovsdb-server"
+    fi
+
+    if daemon_is_running ovs-vswitchd; then
+        echo "ovs-vswitchd is already running"
+    else
+        echo "Starting ovs-vswitchd"
+        /usr/share/openvswitch/scripts/ovs-ctl --no-ovsdb-server --system-id=random start --db-file=$OVS_DB_FILE
+        echo "Started ovs-vswitchd"
+    fi
+}
+
+start_ovs
+
+# init bridge
+echo "init bridge"
 AGENT_CONFIG_PATH=/var/lib/everoute/agentconfig.yaml
 
 LOCAL_TO_POLICY_OFPORT=101
@@ -31,13 +63,9 @@ UPLINK_TO_CLS_PATCH="uplink-to-cls"
 DEFAULT_BRIDGE=`cat ${AGENT_CONFIG_PATH} | grep datapathConfig: -A1 | grep -v datapathConfig: | awk -F ':' '{print $1}' | awk '$1=$1'`
 GW_IFACE=${DEFAULT_BRIDGE}-gw
 
-ovs-vsctl del-br ${DEFAULT_BRIDGE}
 ovs-vsctl add-br ${DEFAULT_BRIDGE} -- set bridge ${DEFAULT_BRIDGE} protocols=OpenFlow10,OpenFlow11,OpenFlow12,OpenFlow13 fail_mode=secure
-ovs-vsctl del-br ${DEFAULT_BRIDGE}-policy
 ovs-vsctl add-br ${DEFAULT_BRIDGE}-policy -- set bridge ${DEFAULT_BRIDGE}-policy protocols=OpenFlow10,OpenFlow11,OpenFlow12,OpenFlow13 fail_mode=secure
-ovs-vsctl del-br ${DEFAULT_BRIDGE}-cls
 ovs-vsctl add-br ${DEFAULT_BRIDGE}-cls -- set bridge ${DEFAULT_BRIDGE}-cls protocols=OpenFlow10,OpenFlow11,OpenFlow12,OpenFlow13 fail_mode=secure
-ovs-vsctl del-br ${DEFAULT_BRIDGE}-uplink
 ovs-vsctl add-br ${DEFAULT_BRIDGE}-uplink -- set bridge ${DEFAULT_BRIDGE}-uplink protocols=OpenFlow10,OpenFlow11,OpenFlow12,OpenFlow13 fail_mode=secure
 
 ip link set ${DEFAULT_BRIDGE} up
@@ -64,3 +92,25 @@ ovs-vsctl \
     -- set interface $CLS_TO_UPLINK_PATCH type=patch options:peer=$UPLINK_TO_CLS_PATCH ofport=$CLS_TO_UPLINK_OFPORT
 
 ovs-vsctl add-port ${DEFAULT_BRIDGE}-uplink ${GW_IFACE} -- set Interface ${GW_IFACE} type=internal -- set Interface ${GW_IFACE} ofport=10
+
+echo "finish init"
+touch /tmp/everoute_agent_init
+
+function check_ovs_status {
+    /usr/share/openvswitch/scripts/ovs-ctl status
+    return $?
+}
+while true; do
+    # we run sleep in the background so that we can immediately exit when we
+    # receive SIGINT / SIGTERM
+    # see https://stackoverflow.com/questions/32041674/linux-how-to-kill-sleep
+    sleep 30 &
+    wait $!
+
+    if ! check_ovs_status > /dev/null ; then
+        # OVS was stopped in the container.
+        echo "OVS was stopped. Starting it again"
+        start_ovs
+    fi
+
+done
